url: "https://newsface.news" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Newsie McNewsface" # the name of your site, e.g. ACME Corp.
collections:
  category:
    output: true
  authors:
    output: true
plugins: [jekyll-paginate]
paginate: 48
paginate_path: /page:num/
timezone: America/New_York
