url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Newsy McNewsface" # the name of your site, e.g. ACME Corp.
collections:
  category:
    output: true
  author:
    output: true
plugins: [jekyll-paginate]
paginate: 48
paginate_path: /page:num/
